runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: always

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  secure: always

- url: /static/
  static_dir: out/static/
  secure: always

- url: /
  static_files: out/index.html
  upload: out/index.html
  secure: always

skip_files:
- node_modules/*
- dist/*
- source/*
- content/*
- view/*
- NotoSerifCJKjp-hinted/*
- .git/*
